#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=3

# Everything this app needs lives in .env.local, not .env.
ENV_FILE=".env.local"

# The library reads existing values verbatim to offer them as defaults, so strip
# the surrounding quotes from any KEY="value" lines first. Without this, an empty
# KEY="" reads back as two literal quote characters and looks like a real value.
if [[ -f "$ENV_FILE" ]]; then
  _tmp=$(mktemp)
  sed -E 's/^([A-Za-z_][A-Za-z0-9_]*)="(.*)"$/\1=\2/' "$ENV_FILE" > "$_tmp"
  mv "$_tmp" "$ENV_FILE"
fi

banner "Lunch Time setup"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Clerk: create the application"
say "Clerk handles sign-in. You'll create a free application and turn on"
say "email sign-in. About two minutes."
printf '\n'
open_url "https://dashboard.clerk.com/apps/new"
step "Sign in to Clerk (or sign up — the free tier is 10,000 users)."
step "Give the application a name, e.g. Lunch Time."
step "Under 'Sign in options', turn ON  Email address."
step "Turn OFF every social provider (Google, GitHub, …) unless you want them."
step "Click 'Create application'."
printf '\n'
note "Email address + the default email code gives passwordless sign-in: people"
note "type their address and paste the 6-digit code Clerk emails them."
pause "Done? Press Enter."

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Clerk: API keys"
say "Clerk shows the keys right after you create the app. If you've navigated"
say "away, they're under Configure → API keys."
printf '\n'
open_url "https://dashboard.clerk.com/last-active?path=api-keys"
step "Copy the Publishable key (starts pk_test_)."
ask NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY "Paste the publishable key:"
step "Reveal and copy the Secret key (starts sk_test_)."
ask_secret CLERK_SECRET_KEY "Paste the secret key:"
printf '\n'
write_env NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY "$NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY"
write_env CLERK_SECRET_KEY "$CLERK_SECRET_KEY"

# Route config — fixed by this app's file layout, not something to ask about.
write_env NEXT_PUBLIC_CLERK_SIGN_IN_URL "/login"
write_env NEXT_PUBLIC_CLERK_SIGN_UP_URL "/sign-up"
write_env NEXT_PUBLIC_CLERK_SIGN_IN_FALLBACK_REDIRECT_URL "/"
write_env NEXT_PUBLIC_CLERK_SIGN_UP_FALLBACK_REDIRECT_URL "/"
pause "Press Enter to continue."

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "You and your bank account"
say "Last one. Who runs lunch, and where does the money go?"
printf '\n'
note "Use the same address you'll sign in with, or /admin stays hidden from you."
ask ADMIN_EMAILS "Your email (comma-separate for several admins):"
write_env ADMIN_EMAILS "$ADMIN_EMAILS"
printf '\n'
say "Bank details drive the VietQR code people scan. You can change these later"
say "at /admin/settings — these only seed the first run."
printf '\n'
note "Bank codes: VCB, TCB, MB, ACB, BIDV, VPB, TPB … full list at api.vietqr.io/v2/banks"
ask DEFAULT_BANK_CODE         "Bank code:"
ask DEFAULT_BANK_ACCOUNT_NO   "Account number:"
ask DEFAULT_BANK_ACCOUNT_NAME "Account holder name (as the bank has it, e.g. NGUYEN VAN A):"
write_env DEFAULT_BANK_CODE         "$DEFAULT_BANK_CODE"
write_env DEFAULT_BANK_ACCOUNT_NO   "$DEFAULT_BANK_ACCOUNT_NO"
write_env DEFAULT_BANK_ACCOUNT_NAME "$DEFAULT_BANK_ACCOUNT_NAME"

finish

printf '  %sNext:%s\n' "$BOLD" "$RESET"
note "  1. Restart the dev server so it picks up the new values:"
note "       pnpm dev"
note "  2. Open http://localhost:3000 and sign up with $ADMIN_EMAILS"
note "  3. Go to Menu, add today's dishes, set the status to 'open'."
printf '\n'
